version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=backend/app.py
      - FLASK_RUN_HOST=0.0.0.0
      - SQLALCHEMY_DATABASE_URI=postgresql://yaakov:Ydavidovici35@db:5432/chess_db
      - PIP_NO_SSL_VERIFY=1
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=development
    working_dir: /app/frontend
    command: ["npm", "run", "dev"]

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: yaakov
      POSTGRES_PASSWORD: Ydavidovici35
      POSTGRES_DB: chess_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
